services:
  - docker
script:
  - docker image build -t mollybowes12/imagetest .
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push mollybowes12/imagetest
